### ISSUE TITLE
Double quotes in shows not contained

### ISSUE THREAD

**Issue by UnderscoreNorth** [assintates/mikan#3]
Shows with double quotes in their name like https://myanimelist.net/anime/31894/The_iDOLMSTER_Million_Live_Dreaming_Animation_PV will cause the json to fail to parse. This also affects shows that have that show in the related section, like https://myanimelist.net/anime/10278/

**Comment by assintates** [comment]
Noted this should be fixed in next deployment also XML is coming in next update

**Comment by assintates** [comment]
Just checked the issue it seems it's not problem with double quotes it's some parse issue cause of some html changes will be fixed in next deployment, also pls not don't confuse jikan and Mikan they are different and they are wrote on different languages.  :smile: :+1:

**Comment by UnderscoreNorth** [comment]
My apologies, I'm trying out both APIs and I copy pasted the issue over.
