### ISSUE TITLE
Error while processing request

### ISSUE THREAD

**Issue by paulo27ms** [assintates/mikan#4]
Request ID: 0HLCBTTV0BR47:00000001
https://initiate.host/anime/36296/

I also have a question about your API, does it cache anything at all or does it always fetch new information?
Also, any limitations on back-to-back requests? I haven't tested much but I only plan to make up to 10~15 requests a day (unless I'm testing things in which case it might go up).
I ask because another API I found cached things for 24 hours, while what I'm doing requires information as up to date as possible, the request limitations is mostly so I know the data gets fetched properly, it's ok if needs a few seconds in between since it'll only be a handful of requests each day.
I tested a few pages and outside of that error all seem to be updated but I'm not sure if it wasn't just because I was the first to request them in a while.

Keep up the good work!

**Comment by assintates** [comment]
For request there's no limitation make as many you want since Mikan uses master and slave config, For cache I don't cache request for long time 1-3 hours max also you can force it to give you live version and re cache after today's deployment (in 4 hours new version will be live to be exact, this function was there in Java version but after porting to c# it got removed) also for search function you can't force it to give you live version 3 hours cache, also I'm trying to fix the error it's caused by html changes for any other request just ask!

**Comment by paulo27ms** [comment]
Cool, thanks for the answers. Looking forward to updates then.

**Comment by paulo27ms** [comment]
If you want other entries to analyze, this one isn't working either now, it worked earlier though: https://initiate.host/anime/36456
Request ID: 0HLCBTTV0BR5U:00000001

**Comment by assintates** [comment]
Thank you for the data! I'll make patch by tonight, also I reduced the cache time to 30 second. Enjoy!

**Comment by paulo27ms** [comment]
Hey, was messing a bit more today and seems like https://initiate.host/anime/36296/ is sadly still broken (Request ID: 0HLCBTTV0BS1B:00000001).
Meanwhile, https://initiate.host/anime/36456 seems to have some odd behavior, it'll work once but if I refresh (F5) it gives an error (Request ID: 0HLCBR9JNTU36:00000001) but if I do a clear cache refresh (CTRL+F5) it'll work (if enough time has passed), I imagine it's an issue related to the cache here.

**Comment by assintates** [comment]
I actually found the issue it's related to how mikan parse the op/Ed if anime Mal has some missing "by" in there data so it causing the split to misbehave, but I had examination on my IoT course so had no time to fix it but I'm gonna work on it today.

**Comment by paulo27ms** [comment]
Don't sweat it, I'm also working on my stuff really on and off, just wanted to make sure you know of current quirks in this project.

**Comment by assintates** [comment]
The Issue has been solved and deployed see release page for changes.
