### ISSUE TITLE
Sometimes error 500 when looking up CCS clear card

### ISSUE THREAD

**Issue by 3hg453** [assintates/mikan#7]
https://initiate.host/anime/33354 (CCS clear card)
Only happens with this and only happens sometimes. It seems only the DIX-US* requests result in error 500

Requests resulting in error 500:
DIX-US1#-1200563577245460354
DIX-US2#-2149379540023486429
DIX-US1#-1198787765529748395

Successful requests:
EBX-JPR1#140570613994021687
EBX-JPR1#140798233138567216
EBX-JPR1#140954208107634101

**Comment by assintates** [comment]
Noted.

Issue: https://sentry.io/share/issue/8d19b11cdae640e58e0181b090d0e21f/

Should be fixed on next update May 19.
